version: '3'
services:
  voice-to-text:
    build: 
      context: .
      dockerfile: dockerfile
    image: "marvinhris/${IMAGE_NAME}"
    env_file:
      - .env
    container_name: "${IMAGE_NAME}-container"
    stdin_open: true
    tty: true
    restart: ${RESTART}
    deploy:
      resources:
        limits:
          memory: ${MEMORY}
    memswap_limit: ${SWAP_LIMIT}
    expose:
      - ${EXPOSE_PORT}
    ports:
      - ${PORT}:${EXPOSE_PORT}
    command: >
      bash -c "gunicorn --workers=${WORKER_TOTAL} --threads=${THREADS} --bind=${HOST}:${EXPOSE_PORT} --worker-class=${WORKER} --timeout=${TIMEOUT} --reload wsgi:server"
  restarter:
    image: docker:cli
    container_name: "${IMAGE_NAME}-restarter"
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 86400; docker restart ${IMAGE_NAME}-container; done"]
    restart: ${RESTART}
