version: '3'
services:
  vtt_fw:
    build: 
      context: .
      dockerfile: dockerfile
    image: marvinhris/vtt_fw:flask_${MODEL_SIZE}
    env_file:
      - small.env
    container_name: ${CONTAINER_NAME}
    working_dir: /${WORK_DIR}
    stdin_open: true
    tty: true
    restart: ${RESTART}
    deploy:
      resources:
        limits:
          memory: ${MEMORY}
    memswap_limit: ${SWAP_LIMIT}
    expose:
      - ${EXPOSE_PORT}
    ports:
      - ${PORT}:${EXPOSE_PORT}
    command: >
      bash -c "gunicorn -w ${WORKER} -b 0.0.0.0:${EXPOSE_PORT} wsgi:server;"

