version: '3'
services:
  vtt_fw:
    build:
      context: .
      dockerfile: dockerfile
    image: marvinhris/vtt_fw:fastapi
    container_name: container_vtt_fw
    working_dir: /app
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - "8080:5000"
    deploy:
      resources:
        limits:
          memory: 8192M
    memswap_limit: 8200M
