version: '3'
services:
  vtt_fw:
    build: 
      context: .
      dockerfile: dockerfile
    image: marvinhris/vtt_fw:flask
    container_name: container_vtt_fw
    working_dir: /app
    stdin_open: true
    tty: true
    restart: always
    deploy:
      resources:
        limits:
          memory: 8192M
    memswap_limit: 8200M
    command: gunicorn -w 4 -b 0.0.0.0:8080 wsgi:server
