apiVersion: v1
kind: Service
metadata:
  name: voice-to-text-service
spec:
  selector:
    app: voice-to-text
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: LoadBalancer
