apiVersion: v1
kind: ConfigMap
metadata:
  name: voice-to-text-configmap
data:

  USERNAME: "marvinhris"
  IMAGE_NAME: "voice-to-text"
  IMAGE: "marvinhris/voice-to-text"
  CONTAINER_NAME: "voice-to-text-container"
  MEMORY: "4096M"
  SWAP_LIMIT: "4100M"
  CPU: "2"
  RESTART: "always"
  PORT: "8080"
  DEBUG: "True"
  UPLOAD_FOLDER: "uploaded_files"
  ALLOWED_EXTENSIONS: "{'wav','mp3'}"
  MODEL_PATH: "/home/data"
  WORKERS: "2"
  THREADS: "2"
  HOST: "0.0.0.0"
  WORKER_CLASS: "gthread"
  TIMEOUT: "60"
  LOG_DIR: "/var/log/gunicorn"
  ACCESS_LOG_FILE: "/var/log/gunicorn/access.log"
  ERROR_LOG_FILE: "/var/log/gunicorn/error.log"
  MAX_REQUESTS: "10"
  LOG_LEVEL: "info"
  EXPOSE_PORT: "5000"
  SLEEP_TIME: "3600"
  RESTARTER_NAME: "voice-to-text-restarter"
